houses:
  - 7.5 # house 1
  - 10.2
  - 2.5
  - 28.6 #house 2
  - -14.5
  - 2.5
  - 42.0 #house 3
  - 11.5
  - 2.5

housesTrue:
  - 7.0 # house 1
  - 10.0
  - 2.5
  - 29.0 #house 2
  - -14.0
  - 2.5
  - 43.0 #house 3
  - 10.5
  - 2.5